#Используйте %player% - для отображения ника игрока, %prefix% - для отображения его префикса, 
#%hearts% - для отображения здоровья игрока, %suffix% - для отображения его суффикса,
#%balance% - для отображения его баланса, & - для цветной надписи и %&% - для отображения знака &.
#'' - для отображения "
text: "&5&k|&d&k|&5&k| &cИгрок &f- %prefix%&f%player% &5&k|&d&k|&5&k|"
#Поставьте значение true для отображения Vault статистики (%prefix%, %suffix%).
vault: true
#Поставьте значение true для отображения Баланса(%balance%) игрока (Зависит от vault).
economy: true
#Поставьте значение true для отображения Текста по привилегии.
#Если у игрока ее нету то отобразится текст сверху.
#Если у игрока есть несколько привилегий из этого списка, то отобразится первая из этого списка.
custom_text: true
custom:
  #Идентификатор текста. Должен быть целым числом от 0, по возрастанию (Заключать в "" или '' не обязательно).
  '0':
    #Сам текст для игрока имеющего привилегию perm.
    text: "&c%player% &aявляется Персоналом || &6Должность &a- %prefix%"
    #Привилегия которую должен иметь игрок чтобы при клике на него отобразился текст.
    perm: "namecheck.stuff"
  "1":
    text: "Hi, it's just test message!"
    perm: "namecheck.test"